### ISSUE TITLE
AskBCS - carousel not working

### ISSUE THREAD

**Issue by PetitsPoissons** [ankurshahi80/food-festival#4]
Hi! So it turns out the newer versions for the bootstrap and jquery npm packages are breaking your app. Putting older versions solved the problem. I just deleted `package-lock.json` and `node_modules`, then changed this in `package.json`:
`	"dependencies": {
		"bootstrap": "^4.3.1",
		"jquery": "^3.4.1",
		"popper.js": "^1.16.0"
	}`

instead of what you had. Then `npm i`, then `npm run build`, and everything worked, carousel included.

**Comment by ankurshahi80** [comment]
Thanks. It worked. :)
